on:
  push:
jobs:
  example:
    runs-on: ubuntu-24.04
    steps:
    - run: ( echo -n 'example=${'; echo -n '{ 1 + 2 }'; echo '}' ) >> "$GITHUB_OUTPUT"
      id: example
    - run: echo '${{ steps.example.outputs.example }}'
